communitiesuk/delta-auth-service

- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/security/ADLdapLoginService.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/LdapService.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaLoginControllerTest.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/OAuthTokenControllerTest.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/RefreshUserInfoControllerTest.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/SamlTokenTest.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/helper/TestLdapUser.kt
Not really useful here, but required for DT-528.
Draft as targeting non-main branch
> LDAP get account enabled from useraccountcontrol

- auth-service/build.gradle.kts
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Routing.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/SecurityHeaders.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/StatusPages.kt
Added caching and CSP headers
Testing: manually checked for headers on status page/login page
> Dt 520 security headers

- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Routing.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaLoginController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaSSOLoginController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/OriginHeaderCheck.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/RegistrationService.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaLoginControllerTest.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/security/OAuthSSOLoginTest.kt
Current method of CSRF protection
> Make origin header check a plugin

- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaResetPasswordController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaSSOLoginController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaSetPasswordController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaUserRegistrationController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/repositories/UserAuditTrailRepo.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/RegistrationService.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserAuditService.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaResetPasswordControllerTest.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaSetPasswordControllerTest.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaUserRegistrationControllerTest.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/security/OAuthSSOLoginTest.kt
* Setting and resetting passwords
* Registration, including SSO user creation
Added tests, haven't done any manual testing though.
It feels like it should be a more service level concern, but the calls to add audit logs fit more neatly into the controller code so I've continued adding it there.
> DT-612 Add auditing for the rest of the existing actions

- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaSSOLoginController.kt
All real people with a levellingup.gov.uk email address should be in the users group, so seeing it should be rare in practice.
> DT-572 Update group missing error message and remove todo

- terraform/modules/auth_service/dashboard.tf
- terraform/modules/auth_service/monitoring.tf
- terraform/modules/fargate/outputs.tf
> Add CloudWatch dashboard

- .github/workflows/publish.yml
- .github/workflows/terraform_deploy.yml
Similar to CPM (https://github.com/communitiesuk/common-payments-module/blob/main/.github/workflows/terraform-deploy.yml). I've set the environment and secrets up, but haven't tested it yet.
> Add GitHub actions job to auto-deploy to test

- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminGetUserController.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminGetUserControllerTest.kt
Change for [this comment](https://github.com/communitiesuk/delta/pull/1376#discussion_r1495427320) on delta PR
> DT-610-3: Error handling change

- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt
See https://github.com/communitiesuk/delta/pull/1398
> DT-277 Switch to new GUID mode

- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/DeltaConfig.kt
> DT-694 updated internal role string

- docker-compose.yml
- terraform/modules/auth_service/database.tf
**This PR:**
- Upgrades the Postgres engine version to 16.1
> DT-817: Postgres version upgrade

- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/AzureADSSOConfig.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/DeltaConfig.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminEditUserController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminEmailController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminEnableDisableUserController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminGetUserController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminUserController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminUserCreationController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/EditRolesController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/AccessGroupsService.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/MemberOfToDeltaRolesMapper.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminEditUserControllerTest.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminEmailControllerTest.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminGetUserControllerTest.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/service/MemberOfToDeltaRolesMapperTest.kt
I'd been meaning to do this for a while. I don't think it's that much better to be honest, but slightly nicer than lots of strings.
> Make SystemRoles an enum

- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Routing.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/EditOrganisationsController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/EditUserDetailsController.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/EditOrganisationsControllerTest.kt
Edit own organisations endpoint
> DT-694 edit organisations endpoint and tests

- .github/workflows/publish.yml
- auth-service/build.gradle.kts
**Description**
updated dependencies
**Testing**
ran tests
> DT-823: updated dependencies

- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Routing.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/EditAccessGroupsController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/EditUserDetailsController.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/EditAccessGroupsControllerTest.kt
**Description** Extra check that user is a member of all organisations provided to the access group update endpoint.
No testing except included unit test.
> DT-694 Add validation user is member of organisation for access group update

- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminEmailController.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/StatusPages.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/repositories/LdapRepository.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/utils/LoggerTimed.kt
Primarily reducing log level of some handled errors from ERROR to WARN.
No testing except running tests, but should all be safe changes.
> Minor error logging updates

- .github/workflows/publish.yml
- auth-service/build.gradle.kts
> DT-984: May patching

- auth-service/build.gradle.kts
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Application.kt
- terraform/modules/auth_service/main.tf
- terraform/modules/auth_service/variables.tf
- terraform/production/main.tf
- terraform/staging/main.tf
- terraform/test/main.tf
**Description** _Brief description of the changes. Include screenshots of frontend changes. The PR title should include a ticket number and a few word title/summary._
**Local testing** _If there's anything you haven't tested, aren't confident in, or think is risky note it here. Make sure there are testing instructions on the ticket before merging._
**Release** _Does this change require any [extra release steps](https://dluhcdigital.atlassian.net/wiki/spaces/DT/pages/3375147/Ticket+specific+release+actions), changes to be deployed in a certain order, or affect other devs? Does any documentation need updating?_
> DT-836 allow CORS for API

- .github/workflows/publish.yml
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Application.kt
**Description** CORS fixes
**Local testing** It works via curl, can't test swagger locally
**Release** noting special on auth service side
> DT-836 don't specify protocol in host

- auth-service/build.gradle.kts
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Application.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Routing.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/ExternalDeltaApiTokenController.kt
- terraform/production/main.tf
- terraform/staging/main.tf
- terraform/test/main.tf
**Description** Remove plugin use manual headers
**Local testing** Needs to be tested with swagger on Test
**Release** Nothing new
> DT-836 manual CORS implementation, remove plugin

- auth-service/build.gradle.kts
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Application.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Routing.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/ExternalDeltaApiTokenController.kt
> DT-836 remove nonexistent CORS imports

- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Application.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Routing.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/DeltaConfig.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/StatusPagesTest.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/security/RateLimitingTest.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/service/EmailServiceTest.kt
- terraform/modules/auth_service/variables.tf
- terraform/production/main.tf
- terraform/staging/main.tf
- terraform/test/main.tf
> DT-836 no schema in API_ORIGIN

- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/OrganisationService.kt
- terraform/production/main.tf
- terraform/staging/main.tf
I've enabled it on test and staging.
> Enable X-Ray on all environments

- .github/workflows/publish.yml
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/security/Security.kt
> Add tracing to Azure AD token request

- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/AzureADSSOConfig.kt
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/EmailService.kt
- auth-service/src/main/resources/templates/thymeleaf/delta-login.html
- auth-service/src/main/resources/templates/thymeleaf/emails/already-a-user.html
- auth-service/src/main/resources/templates/thymeleaf/emails/fragments/template.html
- auth-service/src/main/resources/templates/thymeleaf/emails/new-user.html
- auth-service/src/main/resources/templates/thymeleaf/emails/no-user-account.html
- auth-service/src/main/resources/templates/thymeleaf/emails/not-yet-enabled-user.html
- auth-service/src/main/resources/templates/thymeleaf/emails/password-never-set.html
- auth-service/src/main/resources/templates/thymeleaf/emails/reset-password.html
- auth-service/src/main/resources/templates/thymeleaf/emails/user-added-to-dclg-in-access-group.html
- auth-service/src/main/resources/templates/thymeleaf/register-user-form.html
- auth-service/src/main/resources/templates/thymeleaf/registration-success.html
- auth-service/src/main/resources/templates/thymeleaf/reset-password-email-sent.html
- terraform/production/main.tf
- terraform/staging/main.tf
- terraform/test/main.tf
**Release** Terraform + app. No downtime
> DT-1135: rename DLUHC -> MHCLG

- .github/workflows/publish.yml
- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/LDAPConfig.kt
**Description** 
Changed limit of TLD from 2-4 to have no limit due to issue with .wales TLDs
**Local testing**
N/A
**Release** 
Kotlin
> allow for longer top level domains

- auth-service/README.md
**Description**
Updated README with db username and password for local auth service db
> updated README with db username and password

- auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaUserRegistrationController.kt
- auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaUserRegistrationControllerTest.kt
**Description** 
Currently validation is incorrect and does allow users to register with a bad character in the name.
**Local testing** 
Added unit test coverage
> DT-1524: Fix for name validation check.

- .github/workflows/publish.yml
> Version bump

- .github/workflows/publish.yml
- auth-service/build.gradle.kts
Rolling back opentelemetry-aws-xray as we are seeing errors
> DT-1839: rolled back opentelemetry-aws-xray
