communitiesuk/delta-auth-service

auth-service/build.gradle.kts, auth-service/gradle.properties, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Application.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Routing.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/LDAPConfig.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/Monitoring.kt, auth-service/src/main/resources/logback.xml
The default call logging is just a message rather than key/value pairs so it's not super useful, but good enough for now, it should be easy to add our own later.
=> Switch to structured JSON logs

auth-service/build.gradle.kts, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/OAuthTokenControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/RefreshUserInfoControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/helper/TestClient.kt
I wanted to be consistent, but Mockito struggles with suspending functions and non-nullable parameters, so switching to <https://mockk.io/>.
=> Switch from Mockito to mockk

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Routing.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/Monitoring.kt
They're very noisy in the logs at the moment.
Plus add a path for /favicon.ico to get rid of some 404s
=> Skip logging healthchecks

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaLoginController.kt
Tested locally, password box is cleared on returning an LDAP error or incorrect password/login details error
=> Remove password from returned pages

terraform/modules/fargate/iam_roles.tf
No change to resources, just changes how state is stored.
PR is just for visibility - this has been applied to prod.
=> Remove redundant count ternary - avoids  Invalid count argument error

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Application.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/SelfSignedSSLCertKeystore.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/ClientConfig.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaLoginController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaSSOLoginController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/OAuthTokenController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/Monitoring.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/security/ADLdapLoginService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/security/LdapAuthenticationService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/security/Security.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/AuthorizationCodeService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/DbPool.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/LdapService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/OAuthSessionService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserLookupService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/tasks/DeleteOldAuthCodes.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/tasks/DeleteOldDeltaSessions.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaLoginControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/OAuthTokenControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/RefreshUserInfoControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/dbintegration/AuthorizationCodeServiceTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/dbintegration/OAuthSessionServiceTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/helper/TestClient.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/security/OAuthLoginTest.kt
Plus a couple of refactors (review commit by commit).
Something I've been lazy about and am coming back to now. From some reading and experimenting:
* Ktor uses Dispatchers.Default for handling requests, which will be 2 threads on prod (it's `max(cpu_cores, 2)`)
* JDBC and Java's LDAP implementation are blocking, so send those off to Dispatchers.IO (which is a bigger thread pool)
* HttpClient (for talking to Microsoft in the OAuth flow) is non-blocking, so don't need to worry about that
I haven't done any load testing as I expect we've got plenty of headroom even without this change.
=> Use IO dispatcher for blocking calls

.github/workflows/publish.yml, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/LDAPConfig.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaLoginController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/security/ADLdapLoginService.kt
Fix for https://dluhcdigital.atlassian.net/browse/MSD-65223.
I'm planning to check it briefly on test, then deploy straight through to production.
=> Allow apostrophes and trim usernames for form login

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/LDAPConfig.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/OAuthTokenController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/Monitoring.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/AccessGroupsService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/LdapService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/MemberOfToDeltaRolesMapper.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/OrganisationService.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/ApplicationTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaSetPasswordControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaUserRegistrationControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/OAuthTokenControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/helper/TestLdapUser.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/security/GroupServiceTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/security/OAuthSSOLoginTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/security/RegistrationServiceTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/security/UserServiceTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/service/MemberOfToDeltaRolesMapperTest.kt
Map the user's groups into a list of Delta roles and access groups.
Given a group like `datamart-delta-some-role-some-org` there's no perfect way of determining which bit is an organisation id vs role, they can both have hyphens in, and there's nothing stopping a role suffix matching an organisation prefix.
I've taken the approach from Delta:
* Get a list of organisation ids from MarkLogic
* Have a hardcoded list of system roles, plus a list of all access groups from AD
* Match the group suffix against an organisation id if possible, longest wins
* Attempt to match the rest of the group name against a system role or access group
Invalid roles get discarded, as do (role, org) memberships where the user isn't part of both the role (datamart-delta-role) and the organisation …
=> DT-553 Map user roles from AD

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/OrganisationService.kt
It doesn't actually take this long, but between it taking a few seconds sometimes and SAML library initialisation blocking out the thread for the rest it sometimes times out for the first login on our tiny 0.25 CPU core test instance.
=> Increase org request timeout to 20s

auth-service/src/main/resources/db/migration/V2.1__password_tokens_dup_index.sql
An identical index was made automatically for the primary key
=> Migration to remove dup index on set_password_tokens user_cn

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/Monitoring.kt, terraform/modules/auth_service/load_balancing.tf, terraform/production/main.tf
Load balancer healthchecks are failing in production. I'm not sure what the cause of this is, the metrics all look healthy and getting the `/health` endpoint through CloudFront returns in <200ms so it's hard to believe it's timing out twice in a row.
Enabling logs for the healthcheck endpoint, bumping up resources and healthcheck timeout to see if that helps.
=> Log healthchecks + increase timeout + cpu + memory

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/RefreshUserInfoController.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/RefreshUserInfoControllerTest.kt
Similar to the OAuth token endpoint.
This code should probably be shared somewhere, I might try and restructure the auth service a bit and find somewhere to put it. Separate PR though.
=> DT-553 Return updated roles with token refresh

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Routing.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/EmailConfig.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/LDAPConfig.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaLoginController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaSetPasswordController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaUserRegistrationController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/Monitoring.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/saml/SAMLTokenService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/security/RateLimiting.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/AuthorizationCodeService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/DbPool.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/EmailService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/GroupService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/OAuthSessionService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/OrganisationService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/RegistrationService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/SetPasswordTokenService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserLookupService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/tasks/DeleteOldAuthCodes.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/tasks/DeleteOldDeltaSessions.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/utils/LoggerTimed.kt, auth-service/src/main/resources/logback.xml, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaUserRegistrationControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/dbintegration/SetPasswordTokenServiceTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/tasks/DeleteOldAuthCodesTest.kt
I think what happened on prod this morning:
* Someone tried to register, and it tried to send an email
* It needed the SSL socket factory setting, it was trying to send to the TLS port over plaintext
* We must not have tested this on staging, sorry I should have done that when testing, I just tried test
* This took a long time/possibly forever to timeout
* If it ever did timeout Ktor's error handler logs CancellationExceptions (from the HTTP request being cancelled) at Debug level, so we wouldn't have seen it
* It's a blocking call on one of the default threads, seems like it kept getting some requests waiting for it
* So then some requests started timing out waiting to be picked up, eventually enough of them did that ECS replaced it, then the next one would work fine until someone tried …
=> Fix SMTP error + add timeout

auth-service/src/main/resources/templates/thymeleaf/emails/fragments/template.html, auth-service/src/main/resources/templates/thymeleaf/reset-password-email-sent.html
Fixes two small issues found in testing:
* Email title appears as `${title}` in the email content in some mail apps
* Email address doesn't appear in confirmation message because of var name typo
Also here are some other observations from testing that I haven't addressed because they're not super important:
* "Reset Password Error" - shouldn't this error appear when you land on the page rather than after you submit the new password? I know the validation has to be done on submit, so probably not worth also validating on page load just to improve UX for a rare scenario
* Request IDs - I think we might be too eager to tell the user to contact support with a request ID. It makes the error message a bit busier/intimidating and we should have a bit more faith in the app - if the system says …
=> DT-569: small fixes from testing

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaLoginController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaSSOLoginController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/RegistrationService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserAuditService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserAuditTrailRepo.kt, auth-service/src/main/resources/db/migration/V4__user_audit.sql, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaLoginControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/dbintegration/UserAuditServiceTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/dbintegration/UserAuditTrailRepoTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/security/OAuthSSOLoginTest.kt
Start adding an audit log, currently only auditing logins.
See [DT-612](https://dluhcdigital.atlassian.net/browse/DT-612) for a HLD.
I think the service (business logic, suspend functions) and repositories (plumbing, in this case database queries that are blocking) pattern fits quite well here. It's nice to divide blocking + suspend, and it should make it easy to combine queries into larger transactions which isn't straightforward at the moment. If everyone else is happy with it I'll do some refactoring of the other services too at some point.
[DT-612]: https://dluhcdigital.atlassian.net/browse/DT-612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DT-612 Audit log

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaSSOLoginController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/FetchUserAuditController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/StatusPages.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/repositories/UserAuditTrailRepo.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserAuditService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/utils/CSVUtil.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/FetchUserAuditControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/dbintegration/UserAuditTrailRepoTest.kt
And (very) basic pagination logic that I'll flesh out when doing the Delta side changes.
I've made the CSV headers dynamic based on the top level attributes of "actionData". This feels slightly crazy, but I can't think of a better way of doing it, returning JSON as a CSV column sounds ugly, and whilst at the moment there's nothing important in there, when we're auditing user changes there will be. I think it would only really be an issue if you wanted to combine or compare audit logs for different users, but I don't see why you would.
=> DT-612 Add CSV audit log export

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/AzureADSSOConfig.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaSSOLoginController.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/security/OAuthSSOLoginTest.kt
The JWTs we get from DLUHC Azure have "communities.gov.uk" as the username, whilst Delta users have "levellingup.gov.uk". We don't get the user's email as part of the JWT, even when we requested the email scope on test.
We could presumably request user info from Microsoft Graph and get the email, but for this case it seems simpler if slightly magic to automatically convert communities -> levellingup during the login process.
I've added a new, optional, "convertFromEmailDomain" parameter to the SSO config which I'll set to "@communities.gov.uk". It's only used during the SSO callback, everything else uses the original domain, so users could still have accounts with @communities.gov.uk email addresses and sign in normally if they wanted.
=> DT-572 Add email domain mapping for Azure SSO

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/sso/SSOOAuthClientProviderLookupService.kt
I haven't tested it, but I'm hoping this will fix the issue where it logs you straight in with your Softwire account when trying to use DLUHC SSO, then errors, when you're also logged in with a communities.gov.uk account.
Documentation here https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow#request-an-authorization-code which isn't very helpful:
> If included, the app skips the email-based discovery process that user goes through on the sign-in page, leading to a slightly more streamlined user experience. For example, sending them to their federated identity provider. Apps can use this parameter during reauthentication, by extracting the tid from a previous sign-in.
Let's see if it works on staging.
=> Send domain_hint with SSO login redirect

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaSSOLoginController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaUserRegistrationController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/StatusPages.kt, auth-service/src/main/resources/templates/thymeleaf/register-user-form.html, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaUserRegistrationControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/security/OAuthSSOLoginTest.kt
A nice to have that we skipped before.
When a user signs in with SSO, and they don't have an associated Delta account, and SSO is not required for their domain (so they don't automatically have an account created) they get redirected to the register page. This change displays a message, and pre-fills the email inputs.
=> DT-572 Display message on register page for non-required SSO

auth-service/gradle.properties, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaResetPasswordController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/StatusPages.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/MemberOfToDeltaRolesMapper.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/service/MemberOfToDeltaRolesMapperTest.kt
[Change error to warn for invalid reset password token](https://github.com/communitiesuk/delta-auth-service/commit/4b4ee9783f109b8a6bc14eef52337068721ce16f)
Keeping the error logs clean
[Explicitly ignore delegate groups](https://github.com/communitiesuk/delta-auth-service/commit/6605e13e00071b2e3461345b65299203b68ed1c9)
I didn't even know how these were supposed to work until recently, as far as I can tell they don't, so explicitly ignore them for now to reduce noisy logs
[Add org.gradle.vfs.watch=false to gradle.properties](https://github.com/communitiesuk/delta-auth-service/commit/ef37cec7ae1a1a13d0652984c71f4ba993f5be15) 
This caused very slow startup of gradle for me on Windows, even when gradle was already running as a daemon, it took ~20 seconds to start doing anything. It probably …
=> Miscellaneous changes - Ignore delegate groups, logging changes, gradle prop

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Routing.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/ClientConfig.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaForgotPasswordController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaLoginController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaUserRegistrationController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/security/Security.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaLoginControllerTest.kt
This currently redirects to Delta's "Sign-in page expired" page. An alternative would be to redirect to `/oauth2/authorization/delta-auth` and have them bounce straight back to the login page, not sure what's better.
=> DT-744 Redirect user to error page if old timestamp passed to login

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Routing.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/OriginHeaderCheck.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaLoginControllerTest.kt
This should nudge users away from Internet Explorer without them having to raise a ticket, and mean it stops appearing in the error logs.
We get someone trying to use IE every couple of weeks, but it doesn't seem to support the `Origin` header which we use for CSRF protection.
=> Give error message on origin header check

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Routing.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/LDAPConfig.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaForgotPasswordController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaResetPasswordController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaSetPasswordController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaUserRegistrationController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminEmailController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/repositories/EmailRepository.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/repositories/UserAuditTrailRepo.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/EmailService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/PasswordTokenService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/RegistrationService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserAuditService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/utils/EmailAddressChecker.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/utils/LoggerTimed.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminEmailControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaForgotPasswordControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaResetPasswordControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaSetPasswordControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaUserRegistrationControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/FetchUserAuditControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/RefreshUserInfoControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/dbintegration/PasswordTokenServiceTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/dbintegration/UserAuditTrailRepoTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/security/RegistrationServiceTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/security/UserServiceTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/service/EmailServiceTest.kt
Set up delta to send the activation and reset password emails triggered by admins through the auth service. Did some refactoring of emails related code. Added tests.
Delta PR to follow shortly.
Splitting the work for the ticket into 2 PRs so this is only the first step in the HLD from the ticket.
Testing: Lots done locally and tests written
Risks: If emails don't send correctly then it could cause an increase in support issues and/or confusion
Documentation: Ticket and this PR (no major changes to the user)
=> DT 610 - Emails through auth service

.github/workflows/publish.yml, auth-service/Dockerfile, terraform/modules/auth_service/main.tf
`openssl x509` only uses the first cert in the file. 
I've manually deployed to test and updated the test SQL cert. Works fine. I wanted to do it with an env var defined in the Dockerfile originally (so that the path is only referenced in one place) but that didn't seem to have any effect.
Will do the same for keycloak in the delta repo.
=> DT-585: use the full postgres CA cert bundle, not just one

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaLoginController.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaLoginControllerTest.kt
Mostly useful on staging since there's no button for the Softwire SSO.
=> Allow empty password for SSO users

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaResetPasswordController.kt
Tiny change.
`UserService::resetPassword` already has some error handling built in. Logging and rethrowing doesn't add much here and was adding noise to error logs for expected issues like disabled users that are already correctly logged at warn level.
=> Remove extra error handling on password reset

auth-service/build.gradle.kts, auth-service/entrypoint.sh, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/repositories/LdapRepository.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/tasks/TaskRunner.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/tasks/UpdateUserGUIDMap.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/utils/UUIDUtils.kt, auth-service/src/main/resources/db/migration/V5__user_guid_map.sql, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminGetUserControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/helper/TestLdapUser.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/utils/UUIDUtilsTest.kt, terraform/modules/auth_service/schedule.tf
Adds a new overnight job to import all user old and actual objectGUIDs into a table in the auth service.
I'm planning to export it as a CSV and load it into MarkLogic to use for updating the objectGUIDs there. We're not doing anything with the map in the auth service, it's mostly a convenient place to add the script.
The job takes a few seconds on test. It will be longer on prod, but I think <30 seconds still. It loads the full list of users into memory twice, but napkin maths says it should be OK.
One annoying thing is that Active Directory renders GUIDs to strings slightly differently to Java given the same bytes. I'm planning to use the Java representation for the strings in MarkLogic since we're expecting to move away from AD anyway long term.
=> DT-277 Map of old to new user objectGUIDs as table

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/repositories/LdapRepository.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/tasks/UpdateUserGUIDMap.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/utils/UUIDUtils.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/utils/UUIDUtilsTest.kt
Looking at your comment in AdUser.java in Delta @hugh-emerson, I think you're right that the byte representation is different and that using ADs string representation gets a "correct" UUID in that the version number is in the right place.
I couldn't find any super clear documentation on this, and I don't think it matters too much, but may as well switch.
=> DT-277 Use AD string representation of GUID

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/RefreshUserInfoController.kt
Without this refreshing user info after updating a role/similar would fail as Delta couldn't parse the response.
The Playwright tests should probably catch this, I'll have a go at adding it.
=> DT-571 Add is_sso to refresh user info response

auth-service/README.md, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/EditRolesController.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/EditRolesControllerTest.kt
Accept a list of roles to add, and a list to remove. This should fix the case where a user has the data certifier (or auditor) role, but doesn't have a certifier/auditor organisation and gets removed from the role because Delta can say which roles it's expecting to get removed.
It's not completely clear that's actually a bug, but it's feels unexpected so let's fix it.
This is a breaking change and requires https://github.com/communitiesuk/delta/pull/1441 to be merged before release.
=> DT-694 Take list of roles to add and remove

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/tasks/UpdateUserGUIDMap.kt, terraform/modules/auth_service/schedule.tf
We could completely delete it, but I'd like to keep the table around for a little while at least just in case we missed anything in the migration.
=> DT-277 Disable UpdateUserGUIDMap job

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/repositories/UserAuditTrailRepo.kt, auth-service/src/main/resources/db/migration/V7__audit_action_update.sql
Currently `getAuditForUser` requires all the actions to be in the enum. This is why we couldn't load the audit for a user in a support ticket earlier today.
=> Migration to update old audit actions

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminEditUserController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminUserCreationController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/DeltaUserDetailsRequest.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/EditUserDetailsController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/MemberOfToDeltaRolesMapper.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserService.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminEditUserControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminUserCreationControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaUserDetailsRequestTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/EditUserAccessGroupsControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/security/UserServiceTest.kt
Add validation to check that the roles, organisations and access groups we get from Delta for the admin create/update user endpoints make sense.
I've separated out the `DeltaUserDetailsRequest` as the untrusted input from Delta, and `DeltaUserPermissions` as the validated list of organisations, roles and access groups. There's a new `DeltaUserPermissionsRequestMapper` to convert one to the other which I've left in the controllers folder, but should maybe be a service? We're getting to the point we've got enough classes the very simple package hierarchy doesn't quite work anymore.
I've added a few tests for it, plus the controllers use the real class so their tests cover it a bit too. I've done a quick test of creating and updating users through Delta including a bulk upload, though I …
=> DT-920 Improve validation when creating and updating users as admin

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminGetUserController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/EditOrganisationsController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/EditRolesController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/MemberOfToDeltaRolesMapper.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserLookupService.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminGetUserControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/EditOrganisationsControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/EditRolesControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/helper/MockUserLookupService.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/service/UserLookupServiceTest.kt
Add a new function to UserLookupService that reads the user from AD and then interprets its roles, access groups etc.
This simplifies a few code paths that previously had to read all organisations and access groups and then call the roles mapper. It hasn't helped as much as I'd hoped, but it should also be easier to migrate to a database where we wouldn't need the list of all organisations and access groups to load a user's roles.
=> Add memberOf to role mapping to userLookupService

terraform/modules/auth_service/monitoring.tf
**Description** Add an alarm based on the "ERROR" level logs metric filter. This might be too noisy at the current threshold, but let's see, hopefully it will help us keep the logs nice and clean too.
**Local testing** Applied to test, looks OK though I haven't tried to set it off.
**Release** Terraform part of normal release process.
=> Add CloudWatch alarm on large number of error logs

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Routing.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminResetMfaTokenController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserService.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminResetMfaTokenControllerTest.kt
**Description** Auth service side of putting MFA reset in the auth service.
**Local testing** Local testing for controller, and service method worked in E2E testing.
**Release** No extra release steps or documentation changes that I am aware of.
=> DT-983 new endpoint for MFA reset plus tests

terraform/production/main.tf
**Description** Enable the new user update notifications on production. Should be roughly co-ordinated with removing the old `mhclg-user-added-to-stats-user-group` part of the ldap-audit which I'll raise a ticket for, though I think it's fine if both are enabled for a bit.
=> DT-629 Enable user update notification emails on production

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/FetchUserAuditController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/repositories/UserAuditTrailRepo.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserAuditService.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/FetchUserAuditControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/dbintegration/UserAuditTrailRepoTest.kt
**Description** Return "totalRecords" with the fetch user audit JSON response, and accept a pageSize query parameter.
**Local testing** Tested locally as part of Delta change
**Release** Auth service only
=> DT-697 Add total number of available records to user audit fetch

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/FetchUserAuditController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/repositories/UserAuditTrailRepo.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserAuditService.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/FetchUserAuditControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/dbintegration/UserAuditTrailRepoTest.kt
**Description** For the "Download audit report" button on the Admin -> Users page in Delta. This can get pretty large on production, but should be fine for a reasonable time range. The query isn't indexed, but the table is still small enough that a full scan is ~seconds.
We could combine this with the other CSV endpoint and make all the parameters optional, but it felt slightly simpler to make it separate.
**Local testing** Tested as part of Delta work.
**Release** Auth service only.
=> DT-697 Add endpoint to get audit CSV for all users

.github/workflows/publish.yml
Original Delta PR: https://github.com/communitiesuk/delta/pull/1539
I've left the GITHUB_TOKEN with read access only, and added a deploy key to give this workflow write access. I haven't tested this so I might not have set it up quite right, but I'll try it once it's merged.
=> DT-942 Push git tag on publish release build

.github/workflows/publish.yml, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaSSOLoginController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminEditUserEmailController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminEditUserNotificationStatusController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminResetMfaTokenController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminUserCreationController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/EditAccessGroupsController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/RefreshUserInfoController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/repositories/UserGUIDMapRepo.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/RegistrationService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserGUIDMapService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/utils/Parameters.kt, auth-service/src/main/resources/db/migration/V11__lowercase_cn.sql, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminEditUserControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminEditUserEmailControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminEditUserNotificationStatusControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminEnableDisableUserControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminGetUserControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminResetMfaTokenControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminUserCreationControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaResetPasswordControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaSetPasswordControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaUserRegistrationControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/EditAccessGroupsControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/FetchUserAuditControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/RefreshUserInfoControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/dbintegration/UserAuditServiceTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/dbintegration/UserGUIDMapTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/security/OAuthSSOLoginTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/security/RegistrationServiceTest.kt
**Description** The current lookup is case-sensitive, which is fine for the internal API, but for SSO login and creating users means they don't match. This doesn't actually cause any issues since it always falls back to looking up in AD, but it means some extra calls and log noise.
I've added a generated column because that seems simplest to understand, but an index on `user_guid_map (LOWER(user_cn))` would presumably work just as well and use less space.
**Local testing** I've tried logging in normally and through SSO, but haven't actually tried one with a different case to reproduce it.
**Release** Auth service only, includes migration
=> DT-976 Case insensitive GUID lookup by email

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Routing.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/ClientConfig.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/ExternalDeltaApiTokenController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/InternalDeltaApiTokenController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/repositories/UserAuditTrailRepo.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/DeltaApiTokenService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserAuditService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/tasks/DeleteOldApiTokens.kt, auth-service/src/main/resources/db/migration/V12__api_tokens.sql, auth-service/src/main/resources/db/migration/V9__api_tokens.sql, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/ExternalDeltaApiTokenControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/InternalDeltaApiTokenControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/service/DeltaApiTokenServiceTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/tasks/DeleteOldApiTokensTest.kt, terraform/modules/auth_service/main.tf, terraform/modules/auth_service/schedule.tf, terraform/modules/auth_service/secrets.tf
**Description** Endpoints in the auth service and service methods to support them.
**Local testing** Automated tests for all new methods and endpoints, and manually tested locally with the gateway.
**Release** The auth service side I don't think entails any changes.
=> Dt 836 move API authentication to the auth service

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/EditLdapGroupsController.kt
As suggested on the ticket. 
**Local testing** I've not tested this.
=> DT-1013: ignore NameAlreadyBoundException

.github/workflows/publish.yml, terraform/production/ci_iam.tf, terraform/production/main.tf
This PR creates the roles and policies required to use OIDC instead of secrets/keys within GitHub Actions.
=> DT-753: Replace GitHub Actions access keys with OIDC

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaSetPasswordController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/AdminEnableDisableUserController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserService.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/AdminEnableDisableUserControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaSetPasswordControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/security/UserServiceTest.kt
**Description** Activate notifications when a user is enabled through a set password email.
Also affects activating an SSO user that doesn't have their password set, this now matches the behaviour when a user does have a password - notifications are activated when the user is enabled.
**Local testing** Unit tests and tried with local delta
**Release** Auth service only, no extra steps
=> DT-1089 Activate notifications when enabled through set password

auth-service/build.gradle.kts, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/Monitoring.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/saml/SAMLTokenService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/OrganisationService.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/sso/MicrosoftGraphService.kt, terraform/modules/fargate/adot-config.yml, terraform/modules/fargate/ecs.tf
**Description** We're getting traces through to X-Ray for test. They mostly look good though I've seen one or two which seem to include spans from other requests and I'm not sure why.
This should (in theory, I haven't tried it on test yet) link up the CloudWatch logs with X-Ray which should make it easier to jump between them and also give a way of investigating these odd traces
**Local testing** Ran locally, no real testing
**Release** Auth service release including terraform apply
=> DT-732 Tracing follow ups

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/RefreshUserInfoController.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/RefreshUserInfoControllerTest.kt
* Remove personal data role when impersonating users for <https://dluhcdigital.atlassian.net/browse/DT-987>
* Return impersonated user GUID so the certifier home page can use it
Unit tests only, haven't tested manually.
=> User impersonation updates

terraform/production/variables.tf, terraform/staging/variables.tf, terraform/test/variables.tf
**Description** Just adding a description to the image_tag tf variable so that devs don't accidentally try running with "21.0" instead of "release-21.0".
**Local testing** Nothing to test
**Release** Nothing to release
=> Small change to add description to image_tag tf variable

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/Injection.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/OAuthTokenController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/internal/RefreshUserInfoController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/repositories/UserAuditTrailRepo.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/UserAuditService.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/OAuthTokenControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/RefreshUserInfoControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/dbintegration/UserAuditServiceTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/dbintegration/UserAuditTrailRepoTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/dbintegration/UserGUIDMapTest.kt
**Description**
Added check to see if a user is new by check the audit logs to see how many times they have logged in. This is then passed to Delta
**Local testing** 
Tested locally
Added unit tests (also added clean up to some pre-existing tests - only for user-audit and user_guid_map tables)
**Release**
Also requires Delta release
=> DT-1374 Add welcome message for new internal users

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/config/DeltaConfig.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaForgotPasswordController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaLoginController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaResetPasswordController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaSetPasswordController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/controllers/external/DeltaUserRegistrationController.kt, auth-service/src/main/kotlin/uk/gov/communities/delta/auth/plugins/OriginHeaderCheck.kt, auth-service/src/main/resources/templates/thymeleaf/delta-login.html, auth-service/src/main/resources/templates/thymeleaf/error.html, auth-service/src/main/resources/templates/thymeleaf/expired-reset-password.html, auth-service/src/main/resources/templates/thymeleaf/expired-set-password.html, auth-service/src/main/resources/templates/thymeleaf/forgot-password.html, auth-service/src/main/resources/templates/thymeleaf/fragments/template.html, auth-service/src/main/resources/templates/thymeleaf/password-form.html, auth-service/src/main/resources/templates/thymeleaf/register-user-form.html, auth-service/src/main/resources/templates/thymeleaf/registration-success.html, auth-service/src/main/resources/templates/thymeleaf/reset-password-email-sent.html, auth-service/src/main/resources/templates/thymeleaf/reset-password-success.html, auth-service/src/main/resources/templates/thymeleaf/set-password-success.html, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/DeltaLoginControllerTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/controllers/StatusPagesTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/security/RateLimitingTest.kt, auth-service/src/test/kotlin/uk/gov/communities/delta/service/EmailServiceTest.kt, terraform/modules/auth_service/main.tf
**Description** 
Added warning that should only appear in non-prod environments
Added noindex to `<head>` that should apply in non-prod environments (feel like we should have this for prod, too?)
**Local testing** 
- Locally tested with switching variable manually
- Unit test coverage
**Release** 
Auth service release
=> DT-1502: non-prod warning text

auth-service/src/main/kotlin/uk/gov/communities/delta/auth/services/EmailService.kt, auth-service/src/main/resources/templates/thymeleaf/emails/already-a-user.html, auth-service/src/main/resources/templates/thymeleaf/emails/no-user-account.html
**Description** 
Similar to https://github.com/communitiesuk/delta-auth-service/pull/199 , this change fixes a broken link in the "already a user" email users receive if they register with an email that already has an account linked to it
=> DT-1565: fixed "forgotten password" link in "already a user" email message

.github/workflows/publish.yml, docker-compose.yml, terraform/modules/fargate/ecs.tf, terraform/staging/.terraform.lock.hcl
43.3 and 44 of otel-sidecar probably have malformed TLS packets, either omitting the SNI or providing the wrong one (I assume, I cannot get onto the otel-sidecar container to run a packet inspector and the AWS firewall TLS logs only log TLS if it is malformed in a way where it cannot be sent at all rather than just triggering our firewall rule), 43.2 does not so we revert to that.
=> Otel sidecar revert
